// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv'
import { defineConfig } from 'prisma/config'

dotenv.config({
  path: '.env',
})

export default defineConfig({
  migrations: {
    seed: 'jiti prisma/seed.ts',
  },
  datasource: {
    url: process.env.PRISMA_DATABASE_URL,
  },
})
